- emitter/README.md
- emitter/broker.yaml
- emitter/service.yaml
Creates a StatefulSet and associated load-balanced Service.
> Step-by-step Emitter K8s StatefulSet.

- k8s/1-provider.tf
- k8s/2-kube-controller.tf
- k8s/3-kube-node.tf
- k8s/backend.tf
- k8s/output.tf
- k8s/vars.tf
Generates a 3-node x86 cluster.
> Terraform-generated k8s from Works on Arm.

- README.md
Update conceptual architecture and backlog items / tasks remaining
> Update conceptual architecture

- README.md
- openfaas/README.md
- openfaas/services/.gitignore
- openfaas/services/README.md
- openfaas/services/db-inserter/handler.js
- openfaas/services/db-inserter/package.json
- openfaas/services/db-reader/handler.js
- openfaas/services/db-reader/package.json
- openfaas/services/render-map/handler.js
- openfaas/services/render-map/package.json
- openfaas/services/stack.yml
* Adds documentation for each function
* Adds 3x OpenFaaS functions
> Add 3x OpenFaaS functions

- openfaas/services/README.md
- openfaas/services/db-inserter/.gitignore
- openfaas/services/db-inserter/handler.js
- openfaas/services/db-inserter/package-lock.json
- openfaas/services/db-inserter/package.json
- openfaas/services/stack.yml
Shows how to create a table/row using a secure Kubernetes secret for the DB connection info.
Tested e2e.
> Add connection for db-inserter function

- openfaas/services/README.md
- openfaas/services/db-inserter/handler.js
- openfaas/services/schema.sql
- openfaas/services/stack.yml
* Add new schema
* Insert new rows with correct JSON example as per README
* Give debugging instructions for OpenFaaS
> Update OpenFaaS DB inserter and initial schema

- README.md
- openfaas/services/.gitignore
- openfaas/services/README.md
- openfaas/services/db-reader/handler.js
- openfaas/services/db-reader/package-lock.json
- openfaas/services/db-reader/package.json
- openfaas/services/stack.yml
* Adds read function for drone_event
* Adds read function for drone_position
* Updates main tasks/backlog
* Documents changes to API and how to invoke
> Complete "db-reader" function for events and positions

- README.md
> Update highlighting for python example

- openfaas/services/README.md
- openfaas/services/db-reader/handler.js
- openfaas/services/stack.yml
* Add support for geoJSON endpoint
This would allow for "live reloading" modifications in the map-render endpoint.
> Add support for geoJSON endpoint

- README.md
- emitter/service.yaml
* Document what is exposed vs private cc @c0dyhi11 @bigeasy 
* Add Emitter NodePort cc @bigeasy
> Document what is exposed vs private and add Emitter NodePort

- README.md
* Add note about needing Docker
cc @c0dyhi11
> Add note about needing Docker

- README.md
- emitter/README.md
Cody wanted user to be able to avoid docker
> Swap docker run for kubectl

- README.md
- grafana/README.md
- grafana/deployment.yaml
- openfaas/grafana-ingress.yaml
* Add DNS instructions 
* Add Ingress for Grafana
> Add DNS instructions and Ingress for Grafana

- openfaas/services/db-reader/handler.js
- openfaas/services/schema.sql
- openfaas/services/stack.yml
* Select only latest drone position for output
* Added Postgresql function
> Add function for database to select only latest position

- README.md
- test/README.md
- test/package.json
- test/src/app.ts
- test/src/drone.ts
- test/src/hangar.ts
- test/src/warehouse.ts
- test/tsconfig.json
- test/tslint.json
See README for details.  Location data is emitted.  Events are not implemented yet.
> Add a test integration

- openfaas/mqtt-connector/README.md
- openfaas/services/README.md
- openfaas/services/db-inserter/handler.js
- openfaas/services/publisher.py
- openfaas/services/schema.sql
- openfaas/services/stack.yml
* Updates schema to add destination and use battery_percent
instead of battery_mv.
* Updates publisher.py to give 2 sec delay between moving drone
on map for user to refresh/view the movement.
* Added drop lines to schema for folks to upgrade who've taken
the schema already. Updated DB function to return new fields.
> Update schema and add insert code for drone_event

- openfaas/services/db-inserter/handler.js
- openfaas/services/db-reader/handler.js
- openfaas/services/render-map/src/Map.js
- openfaas/services/stack.yml
- test/.gitignore
* Updates Mapbox to render GeoJSON source in "realtime" which is
for practical purposes, every 1.5s as defined in Map.js.
> Make map work in "realtime"

- k8s/README.md
- openfaas/README.md
- openfaas/services/db-inserter/handler.js
- openfaas/services/stack.yml
* Auto-scales based upon the expected dataset from the test folder.
* Updates cluster size to be at least 3 nodes, 1 node is an
unrealistic configuration.
> Tune cluster size / auto-scaling

- README.md
- test/README.md
* Add test instructions for emitter forwarded from Kubernetes
* Update note for development users where TLS is optional
> Update notes for deployment

- openfaas/services/README.md
- openfaas/services/db-inserter/handler.js
Fix syntax error in db-inserter - thanks @kit-klein for finding this.
> Fix syntax error in db-inserter

- emitter/README.md
> Update feedback from Kit

- test/README.md
- test/src/drone.ts
- test/src/listener.ts
This PR adds support for `system_error` events - which are randomly generated.  It also now calculates the temperature around the drone based on altitude and randomness.
A listener module was added to src which can be used to locally monitor the position and event data coming from emitter.
> More interesting drones

- test/README.md
- test/src/app.ts
- test/src/atc.ts
- test/src/drone.ts
- test/src/listener.ts
This adds an air traffic control module which monitors drones and sents control events to manage altitude and avoid collisions.  This module can be incorporated into a server side function to manage drones and react to trajectory conflicts.
> add system_warning events, add traffic controller module

- openfaas/services/mqtt-publisher/handler.js
- openfaas/services/stack.yml
* Fix bug where publisher gave "no action" in response
* Move stack.yml from my personal account to an org (`packetiotdemo`)
> Move stack.yml to org

- openfaas/services/render-map/src/Map.js
- test/client/src/app.ts
Relocate NW Vegas further West. Match warehouse icon locations on map to
the locations specified in test.
> Relocate NW Vegas, match icons.
